#### This file is generated by the Fault mapping tool ####
#### Can be edited manually! ####

package LIFT_PROJECT;

##########################################################

##########################################################

$Defaults->{'Mapping_FAULT'} = {
	
##########################################################

##########################################################
	'KEY1B' => {
		'SUBKEYA' => '0xx',	#COMMAND
		'SUBKEYB' => 'xx7',	#COMMAND
		'SUBKEYC' => '123',	#COMMAND     
	},

	'EXCEPT' =>
	  {
		'NOUSE' => 'NOUSE',	#COMMAND
		'NOUSE' => 'NOUSE',	#COMMAND
	  },
	  
	'rb_KEY1A_flt' => {
		'DTC'                       => '0x11111',
		'Device'                    => 'aaaaaaaaaa',
		'DeviceType'                => 'aaaaaaaaaa',
		'Condition'                 => 'aaaaaaaaaa',
		'Unlearn'                   => '',
		'Faultpriority'             => '4',
		'WarningLamp'               => 'Latch',
		'CyclicQualificationtime'   => '10000',                                                           #in ms
		'CyclicDequalificationtime' => 'n/a',                                                            #in ms
		'InitQualificationtime'     => 'n/a',                                                            #in ms
		'InitDequalificationtime'   => 'Init',                                                           #in ms
		'FaultType'                 => 'On Event',
		'Tolerance'                 => '10',                                                               #in ms
		'Suppression'               => 'False',
		'AdditionalFaults'          => ['rb_faulta_flt'],
		'OptionalFault'             => ['rb_faultb_flt'],
		'SupportProjects'           => [ 'MD1', 'MD2', 'MD3', 'MD4' ],
	},
#----------------------------------------------------------------------------------#
	'rb_KEY1B_flt' => {
		'DTC'                       => '0x155544',
		'Device'                    => 'aaaaaaaaaa',
		'DeviceType'                => 'aaaaaaaaaa',
		'Condition'                 => 'aaaaaaaaaa',
		'Unlearn'                   => '',
		'Faultpriority'             => '4',
		'WarningLamp'               => 'Filtered/Latched',
		'CyclicQualificationtime'   => '100',                                                           #in ms
		'CyclicDequalificationtime' => '100',                                                            #in ms
		'InitQualificationtime'     => 'n/a',                                                            #in ms
		'InitDequalificationtime'   => 'n/a',                                                           #in ms
		'FaultType'                 => 'cycle',
		'Tolerance'                 => '5',                                                               #in ms
		'Suppression'               => 'pass',
		'AdditionalFaults'          => ['rb_faultc_flt'],
		'OptionalFault'             => ['rb_faultd_flt'],
		'SupportProjects'           => [ 'b1', 'b99' ],
	},
#----------------------------------------------------------------------------------#
	'rb_KEY1C_flt' => {
		'DTC'                       => '0x22222',
		'Device'                    => 'ss',
		'DeviceType'                => 'ss',
		'Condition'                 => 'g4',
		'Unlearn'                   => 'abc',
		'Faultpriority'             => '5',
		'WarningLamp'               => 'Latched',
		'CyclicQualificationtime'   => 'n/a',                                                           #in ms
		'CyclicDequalificationtime' => 'n/a',                                                            #in ms
		'InitQualificationtime'     => 'Init',                                                            #in ms
		'InitDequalificationtime'   => 'Init',                                                           #in ms
		'FaultType'                 => 'On Event',
		'Tolerance'                 => '10',                                                               #in ms
		'Suppression'               => 'False',
		'AdditionalFaults'          => ['rb_faultaa_flt'],
		'OptionalFault'             => ['rb_faultb12_flt'],
		'SupportProjects'           => [ 'B59' ],
	},	
};
1;
