#### This file is generated by the Fault mapping tool ####
#### Can be edited manually! ####

package LIFT_PROJECT;

##########################################################

##########################################################

$Defaults->{'Mapping_FAULT'} = {
	
##########################################################

##########################################################
	'KEY1B' => {
		'SUBKEYA' => '0xx',	#COMMAND
		'SUBKEYB' => 'xx7',	#COMMAND
		'SUBKEYC' => '123',	#COMMAND     
	},

	'EXCEPT' =>
	  {
		'NOUSE' => 'NOUSE',	#COMMAND
		'NOUSE' => 'NOUSE',	#COMMAND
	  },
	  
	'rb_KEY1A_flt' => {
		'DTC'                       => 'n/a',
		'Device'                    => 'sq',
		'DeviceType'                => 'sq',
		'Condition'                 => 'pb',
		'Unlearn'                   => 'n/a',
		'Faultpriority'             => 'n/a',
		'WarningLamp'               => 'n/a',
		'CyclicQualificationtime'   => 'n/a',                                                           #in ms
		'CyclicDequalificationtime' => 'n/a',                                                            #in ms
		'InitQualificationtime'     => 'n/a',                                                            #in ms
		'InitDequalificationtime'   => 'n/a',                                                           #in ms
		'FaultType'                 => 'n/a',
		'Tolerance'                 => 'n/a',                                                               #in ms
		'Suppression'               => 'n/a',
		'AdditionalFaults'          => ['rb_faulta_flt'],
		'OptionalFault'             => ['rb_faultb_flt'],
		'SupportProjects'           => [],
	},
#----------------------------------------------------------------------------------#
	'rb_KEY1B_flt' => {
		'DTC'                       => 'n/a',
		'Device'                    => 'sw',
		'DeviceType'                => 'sw',
		'Condition'                 => 'pb',
		'Unlearn'                   => 'n/a',
		'Faultpriority'             => 'n/a',
		'WarningLamp'               => 'n/a',
		'CyclicQualificationtime'   => 'n/a',                                                           #in ms
		'CyclicDequalificationtime' => 'n/a',                                                            #in ms
		'InitQualificationtime'     => 'n/a',                                                            #in ms
		'InitDequalificationtime'   => 'n/a',                                                           #in ms
		'FaultType'                 => 'n/a',
		'Tolerance'                 => 'n/a',                                                               #in ms
		'Suppression'               => 'n/a',
		'AdditionalFaults'          => ['rb_fault1_flt'],
		'OptionalFault'             => ['rb_fault2_flt'],
		'SupportProjects'           => [],
	},
#----------------------------------------------------------------------------------#
	'rb_KEY1C_flt' => {
		'DTC'                       => 'n/a',
		'Device'                    => 'ss',
		'DeviceType'                => 'ss',
		'Condition'                 => 'g4',
		'Unlearn'                   => 'n/a',
		'Faultpriority'             => 'n/a',
		'WarningLamp'               => 'n/a',
		'CyclicQualificationtime'   => 'n/a',                                                           #in ms
		'CyclicDequalificationtime' => 'n/a',                                                            #in ms
		'InitQualificationtime'     => 'n/a',                                                            #in ms
		'InitDequalificationtime'   => 'n/a',                                                           #in ms
		'FaultType'                 => 'n/a',
		'Tolerance'                 => 'n/a',                                                               #in ms
		'Suppression'               => 'n/a',
		'AdditionalFaults'          => ['rb_fault1a_flt'],
		'OptionalFault'             => ['rb_fault2b_flt'],
		'SupportProjects'           => [],
};
1;
